[tool.poetry]
name = "config-generation"
version = "0.1.0"
description = ""
authors = ["Manacho <manuel.manriquez.b@usach.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
